alias: Värme höj lite vid billig el
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.elpris_billigaste_6_timmar
    to: 'on'
condition:
  - condition: numeric_state
    entity_id: sensor.nordpool_kwh_se3_sek_3_10_025
    attribute: current_price
    below: '1'
action:
  - service: climate.set_temperature
    data:
      temperature: 21
    target:
      entity_id: climate.heat
  - service: climate.set_temperature
    data:
      target_temp_high: 65
      target_temp_low: 50
    target:
      entity_id: climate.tap_water
  - service: climate.set_temperature
    data:
      temperature: 27
    target:
      entity_id: climate.badrum_overvaning
mode: single

===================================================================
alias: Värme sänk vid högt elpris
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.elpris_dyraste_6_timmar
    to: 'on'
condition:
  - condition: numeric_state
    entity_id: sensor.nordpool_kwh_se3_sek_3_10_025
    attribute: current_price
    above: '1'
action:
  - service: climate.set_temperature
    data:
      temperature: 18
    target:
      entity_id: climate.heat
  - service: climate.set_temperature
    data:
      temperature: 17
    target:
      entity_id: climate.badrum_overvaning
  - service: climate.set_temperature
    data:
      target_temp_high: 40
      target_temp_low: 35
    target:
      entity_id: climate.tap_water
mode: single

===================================================================
alias: Värme återställ vid normalt elpris
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.elpris_medium_12_timmar
    to: 'on'
condition: []
action:
  - service: climate.set_temperature
    data:
      temperature: 20
    target:
      entity_id: climate.heat
  - service: climate.set_temperature
    data:
      target_temp_high: 60
      target_temp_low: 50
    target:
      entity_id: climate.tap_water
  - service: climate.set_temperature
    data:
      temperature: 25
    target:
      entity_id: climate.badrum_overvaning
mode: single
